[workspace]
authors = ["Guillaume Witz <guillaume.witz@unibe.ch>"]
channels = ["conda-forge"]
name = "DSPy2026"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = "*"
pandas = "*"
seaborn = "*"
pytorch = "*"
scikit-image = "*"
dash = "*"
jupyterlab = "*"
pip = "*"

[pypi-dependencies]
openpyxl = "*"
